/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangun_datar;

/**
 *
 * @author ACER E15
 */
public class Trapesium extends javax.swing.JFrame {
    double atas, bawah, tinggi, sisi1, sisi2, keliling, luas;
    /**
     * Creates new form Trapesium
     */
    public Trapesium() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LJududl = new javax.swing.JLabel();
        LAtas = new javax.swing.JLabel();
        TfAtas = new javax.swing.JTextField();
        LTinggi = new javax.swing.JLabel();
        TfTinggi = new javax.swing.JTextField();
        LSisi1 = new javax.swing.JLabel();
        LSisi2 = new javax.swing.JLabel();
        TfSisi1 = new javax.swing.JTextField();
        TfSisi2 = new javax.swing.JTextField();
        LBawah = new javax.swing.JLabel();
        Hitung1 = new javax.swing.JButton();
        LKeliling = new javax.swing.JLabel();
        TfKeliling = new javax.swing.JTextField();
        LLuas = new javax.swing.JLabel();
        TfLuas = new javax.swing.JTextField();
        hapus1 = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        TfBawah = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LJududl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LJududl.setText("TRAPESIUM");

        LAtas.setText("ATAS          :");
        LAtas.setToolTipText("");
        LAtas.setFocusable(false);
        LAtas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        TfAtas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfAtasActionPerformed(evt);
            }
        });

        LTinggi.setText("TINGGI       :");
        LTinggi.setToolTipText("");
        LTinggi.setFocusable(false);
        LTinggi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        TfTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfTinggiActionPerformed(evt);
            }
        });

        LSisi1.setText("SISI 1        :");
        LSisi1.setToolTipText("");
        LSisi1.setFocusable(false);
        LSisi1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        LSisi2.setText("SISI 2        :");
        LSisi2.setToolTipText("");
        LSisi2.setFocusable(false);
        LSisi2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        TfSisi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfSisi1ActionPerformed(evt);
            }
        });

        TfSisi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfSisi2ActionPerformed(evt);
            }
        });

        LBawah.setText("BAWAH      :");
        LBawah.setToolTipText("");
        LBawah.setFocusable(false);
        LBawah.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Hitung1.setText("HITUNG");
        Hitung1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hitung1ActionPerformed(evt);
            }
        });

        LKeliling.setText(" KELILING     :");

        TfKeliling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfKelilingActionPerformed(evt);
            }
        });

        LLuas.setText(" LUAS            :");

        hapus1.setText("HAPUS");
        hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus1ActionPerformed(evt);
            }
        });

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        TfBawah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfBawahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LLuas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfKeliling)
                            .addComponent(TfLuas))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(LJududl))
                            .addComponent(LTinggi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(LAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LBawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(LSisi1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfSisi1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TfTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TfBawah, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TfAtas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TfSisi2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LSisi2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(hapus1)
                        .addGap(42, 42, 42)
                        .addComponent(keluar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(Hitung1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJududl)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LAtas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfAtas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBawah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfBawah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfTinggi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LSisi1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfSisi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LSisi2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfSisi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Hitung1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LLuas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus1)
                    .addComponent(keluar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfAtasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfAtasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfAtasActionPerformed

    private void TfTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfTinggiActionPerformed

    private void TfSisi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfSisi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfSisi1ActionPerformed

    private void TfSisi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfSisi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfSisi2ActionPerformed

    private void Hitung1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hitung1ActionPerformed
        // TODO add your handling code here:
        atas = Double.parseDouble(TfAtas.getText());
        bawah = Double.parseDouble(TfBawah.getText());
        tinggi = Double.parseDouble(TfTinggi.getText());
        sisi1 = Double.parseDouble(TfSisi1.getText());
        sisi2 = Double.parseDouble(TfSisi2.getText());
        luas = (atas+bawah)*tinggi/2;
        TfLuas.setText(String.valueOf(luas));
        keliling = sisi1+sisi2+atas+bawah;
        TfKeliling.setText(String.valueOf(keliling));
    }//GEN-LAST:event_Hitung1ActionPerformed

    private void TfKelilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfKelilingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfKelilingActionPerformed

    private void hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus1ActionPerformed
        // TODO add your handling code here:
        TfAtas.setText(String.valueOf(" "));
        TfBawah.setText(String.valueOf(" "));
        TfSisi1.setText(String.valueOf(" "));
        TfSisi2.setText(String.valueOf(" "));
        TfTinggi.setText(String.valueOf(" "));
        TfKeliling.setText(String.valueOf(" "));
        TfLuas.setText(String.valueOf(" "));
    }//GEN-LAST:event_hapus1ActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
       BangunDatar formBangunDatar=new BangunDatar();
        formBangunDatar.show();
        this.hide();
    }//GEN-LAST:event_keluarActionPerformed

    private void TfBawahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfBawahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfBawahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trapesium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trapesium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trapesium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trapesium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trapesium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung1;
    private javax.swing.JLabel LAtas;
    private javax.swing.JLabel LBawah;
    private javax.swing.JLabel LJududl;
    private javax.swing.JLabel LKeliling;
    private javax.swing.JLabel LLuas;
    private javax.swing.JLabel LSisi1;
    private javax.swing.JLabel LSisi2;
    private javax.swing.JLabel LTinggi;
    private javax.swing.JTextField TfAtas;
    private javax.swing.JTextField TfBawah;
    private javax.swing.JTextField TfKeliling;
    private javax.swing.JTextField TfLuas;
    private javax.swing.JTextField TfSisi1;
    private javax.swing.JTextField TfSisi2;
    private javax.swing.JTextField TfTinggi;
    private javax.swing.JButton hapus1;
    private javax.swing.JButton keluar;
    // End of variables declaration//GEN-END:variables
}
